name: "schedule check and build"
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  schedule:
    - cron: "0 6 3,18 * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Get the remote version
      id: remote_version
      uses: cityoflosangeles/fetch-latest-github-release@v3
      with:
        repo_path: "715209/nginx-obs-automatic-low-bitrate-switching"
        github_token: ${{ github.token }}
    - name: Set ENVs variable
      id: version_step
      run: |
        echo "SAVED_RELEASE_VERSION=$(cat dependencies/noalbs-version)" >> $GITHUB_ENV
        echo "RELEASE_VERSION=${{ steps.remote_version.outputs.tag_name }}" >> $GITHUB_ENV
        # Ursprüngliche Version definieren
        VERSION="${{ env.RELEASE_VERSION }}"
        # Das führende 'v' entfernen, falls vorhanden
        CLEAN_VERSION="${VERSION#v}"
        # Am Punkt (.) aufteilen
        IFS='.' read -r MAJOR MINOR PATCH <<< "$CLEAN_VERSION"    
        # Werte in die GitHub-Ausgabe (Outputs) schreiben
        echo "MAJOR=$MAJOR" >> $GITHUB_ENV
        echo "MINOR=$MINOR" >> $GITHUB_ENV
        echo "PATCH=$PATCH" >> $GITHUB_ENV
    - name: Echo the saved version
      run: echo ${{ env.SAVED_RELEASE_VERSION }}
    - name: The remote Version
      run: echo ${{ env.RELEASE_VERSION }}
    - name: Commit if not the same
      if: ${{ env.RELEASE_VERSION != env.SAVED_RELEASE_VERSION }}
      run: echo "${{ env.RELEASE_VERSION }}" > dependencies/noalbs-version
# Build the new way (Docker) 
    - name: Set up QEMU
      if: ${{ env.RELEASE_VERSION != env.SAVED_RELEASE_VERSION || github.event_name == 'pull_request' }}
      uses: docker/setup-qemu-action@v4
    - name: Set up Docker Buildx
      if: ${{ env.RELEASE_VERSION != env.SAVED_RELEASE_VERSION || github.event_name == 'pull_request' }}
      uses: docker/setup-buildx-action@v4
    - name: Login to DockerHub
      if: ${{ env.RELEASE_VERSION != env.SAVED_RELEASE_VERSION || github.event_name == 'pull_request' }}
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build on pull request
      if: ${{ github.event_name == 'pull_request' }}
      uses: docker/build-push-action@v7
      with:
        push: false
        tags: |
          dersni/docker-noalbs:latest,
          dersni/docker-noalbs:v${{ env.MAJOR }},
          dersni/docker-noalbs:v${{ env.MAJOR }}.${{ env.MINOR }},
          dersni/docker-noalbs:v${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }},
          dersni/docker-noalbs:v${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}-${{ github.run_number }}
    - name: Build and push
      if: ${{ env.RELEASE_VERSION != env.SAVED_RELEASE_VERSION && github.event_name != 'pull_request' }}
      uses: docker/build-push-action@v7
      with:
        push: true
        tags: |
          dersni/docker-noalbs:latest,
          dersni/docker-noalbs:v${{ env.MAJOR }},
          dersni/docker-noalbs:v${{ env.MAJOR }}.${{ env.MINOR }},
          dersni/docker-noalbs:v${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }},
          dersni/docker-noalbs:v${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}-${{ github.run_number }}
# commit
    - name: Commit changes an push it to remote
      if: ${{ env.RELEASE_VERSION != env.SAVED_RELEASE_VERSION && github.event_name != 'pull_request' }}
      uses: actions-x/commit@v6
      with:
        email: 41898282+github-actions[bot]@users.noreply.github.com
        name: GitHub Actions
        branch: main
        files: dependencies/noalbs-version
        repository: https://github.com/DjSni/docker-NOALBS
        token: ${{ secrets.GITHUB_TOKEN }}
        force: false
